name: Docs

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "learn/**"
      - ".github/workflows/docs.yaml"

env:
  # Repository specific variables
  REPO_NAME: starship
  DOCS_DEST_PATH: pages/starship
  LEARN_DEST_PATH: src/data/learn/starship

jobs:
  docs-deploy:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified, 'docs/') || contains(github.event.head_commit.added, 'docs/')

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone docs repository
        run: git clone https://x-access-token:${{ secrets.GH_HYPERWEB_PAT }}@github.com/hyperweb-io/docs.hyperweb.io.git external-docs

      - name: Sync the docs
        run: |
          rsync -av --delete ./docs/ ./external-docs/${{ env.DOCS_DEST_PATH }}/
          cd external-docs
          git config user.name 'GitHub Action'
          git config user.email 'action@github.com'
          git add .
          if git diff --cached --quiet; then
              echo "No changes to commit."
          else
              git commit -m "Automated: Update ${{ env.REPO_NAME }} documentation"
              git push
          fi

  learn-deploy:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified, 'learn/') || contains(github.event.head_commit.added, 'learn/')

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone learn repository
        run: git clone https://x-access-token:${{ secrets.GH_HYPERWEB_PAT }}@github.com/hyperweb-io/hyperweb.io.git learn-site

      - name: Create destination directory
        run: |
          mkdir -p ./learn-site/${{ env.LEARN_DEST_PATH }}

      - name: Sync the learn content
        run: |
          rsync -av --delete ./learn/ ./learn-site/${{ env.LEARN_DEST_PATH }}/
          cd learn-site
          git config user.name 'GitHub Action'
          git config user.email 'action@github.com'
          git add .
          if git diff --cached --quiet; then
              echo "No changes to commit."
          else
              git commit -m "Automated: Update ${{ env.REPO_NAME }} learn content"
              git push
          fi
